### ISSUE TITLE
Potential deadlock

### ISSUE THREAD

**Issue by kat-co** [SahilKang/cl-rdkafka#58]
I have a consumer-only system which is utilizing `lparallel` to create a handful of threads. One of the threads calls `kf:poll` in a loop. Another thead is processing these messages, and when done is calling `kf:commit`. I noticed that -- seemingly randomly -- the pipeline I had established stops working.

I narrowed it down to determine it was blocking on the call to `kf:commit`, so I began placing `format` statements to narrow down where. This led me to the attempts to acquire a lock on `+address->queue-lock+`. The `format` statements seem to suggest a deadlock between `poll-loop` and `enqueue-payload`.

```
enqueue-payload: Attempting to hold lock.
poll-loop: Attempting to hold lock.
poll-loop: Lock held
```
(keep in mind output to stdio can arrive at different times)

`enqueue-payload` never reports that it's successfully acquired the lock, and `poll-loop` never reports that it's released the lock. I'm having trouble determining what shared resource the two stacks are sharing.

I am attempting to create a reproducible test-case, but I wanted to submit this information early to see if maybe anyone had some ideas.

**Comment by SahilKang** [comment]
Thanks for digging in and sharing the details :100:; I'm able to reproduce this some of the time with:

```lisp
(ql:quickload '(cl-rdkafka babel))


(defparameter +topic+ "test-topic")

(defparameter +num-messages+ 100000)

(let ((producer (make-instance
                 'kf:producer
                 :conf '("bootstrap.servers" "127.0.0.1:9092")
                 :serde #'babel:string-to-octets)))
  (loop
     repeat +num-messages+
     do (kf:send producer +topic+ "test-message"))
  (kf:flush producer))


(defparameter +consumer+
  (make-instance
   'kf:consumer
   :conf '("bootstrap.servers" "127.0.0.1:9092"
           "group.id" "test-group-id"
           "enable.auto.commit" "false"
           "auto.offset.reset" "earliest"
           "offset.store.method" "broker"
           "enable.partition.eof" "false")
   :serde #'babel:octets-to-string))

(kf:subscribe +consumer+ +topic+)

(defparameter *count* 0)

(defparameter +lock+ (bt:make-lock "+lock+"))

(defparameter +channel+
  (let ((lparallel:*kernel*
         (lparallel:make-kernel 3 :name "test-kernel")))
    (lparallel:make-channel)))

(defun process ()
  (bt:with-lock-held (+lock+)
    (incf *count*)
    (kf:commit +consumer+ :asyncp t)))

(defun poll ()
  (let (message)
    (bt:with-lock-held (+lock+)
      (setf message (kf:poll +consumer+ 5)))
    (when message
      (lparallel:submit-task +channel+ #'process))))


(lparallel:submit-task
 +channel+
 (lambda ()
   (loop
      repeat +num-messages+
      do (poll))))
```

Running `(bt:all-threads)` will sometimes show that all the threads are running okay, but other times I'll see the deadlock you described:

```lisp
#<SB-THREAD:THREAD "worker" waiting on:
      #<MUTEX "address->queue-lock"
          owner: #<SB-THREAD:THREAD "cl-rdkafka" RUNNING {100271A6E3}>>
    {1005DB8F93}>
```

The reason why `poll-loop` won't release the lock is because [this lparallel.queue:pop-queue call](https://github.com/SahilKang/cl-rdkafka/blob/9119880aa85382ce815d7ee0dd404f29ec4b6136/src/high-level/consumer/consumer.lisp#L127) will block indefinitely when the queue is empty. it's not a valid state to reach this call with an empty queue and the reason why it's occurring is because the [commit call](https://github.com/SahilKang/cl-rdkafka/blob/9119880aa85382ce815d7ee0dd404f29ec4b6136/src/high-level/consumer/consumer.lisp#L259) is not grabbing the mutex early enough: the mutex should be grabbed before the `cl-rdkafka/ll:rd-kafka-commit-queue` call a few lines above it.

I'll go into more details in the PR/commit that fixes this, but at a high level:
* [this cl-rdkafka/ll:rd-kafka-commit-queue call](https://github.com/SahilKang/cl-rdkafka/blob/9119880aa85382ce815d7ee0dd404f29ec4b6136/src/high-level/consumer/consumer.lisp#L250) adds more events to the `rd-kafka-queue` without grabbing the mutex
* this causes [process-events](https://github.com/SahilKang/cl-rdkafka/blob/9119880aa85382ce815d7ee0dd404f29ec4b6136/src/high-level/event-io/kernel.lisp#L77) to keep looping (`process-events` is called by `poll-loop`)
* [this enqueue-payload](https://github.com/SahilKang/cl-rdkafka/blob/9119880aa85382ce815d7ee0dd404f29ec4b6136/src/high-level/consumer/consumer.lisp#L259) will attempt to acquire the mutex but will be blocked because `process-events` is still looping with the lock acquired
* eventually [this lparallel.queue:pop-queue call](https://github.com/SahilKang/cl-rdkafka/blob/9119880aa85382ce815d7ee0dd404f29ec4b6136/src/high-level/consumer/consumer.lisp#L127), which is called by `process-events`, blocks on an empty queue
* since `enqueue-payload` is the function which adds elements to this empty queue and since it's blocked while acquiring the mutex, we end up with a deadlock

For analogous reasons, a similar oversight also causes the same deadlock with the [producer send method](https://github.com/SahilKang/cl-rdkafka/blob/9119880aa85382ce815d7ee0dd404f29ec4b6136/src/high-level/producer.lisp#L254), so you get a double whammy :trophy:
