### ISSUE TITLE
It would be cool to change the license to more liberal to make it possible to use the library in the closed-source projects

### ISSUE THREAD

**Issue by svetlyak40wt** [SahilKang/cl-rdkafka#74]
I suggest to take a look at LLGPL (LGPL with [notes](https://opensource.franz.com/preamble.html) about it's application to the lisp code. Or maybe a more permissive license like BSD which is used by C library librdkafka.

**Comment by SahilKang** [comment]
I'm a fan of the gpl for the projects I release myself, and I'm no longer the sole copyright owner of this code so I can't change the license single-handedly

for your own closed-source projects, as long as you're not distributing binaries containing `cl-rdkafka` code, you shouldn't have to license those user-distributed binaries under the gpl...and you're most likely not distributing such binaries to your users since kafka clusters aren't usually exposed to the public internet :)

**Comment by svetlyak40wt** [comment]
Do you mean that GPL library can be linked into some server-side binary and other code of this project should not be licensed as GPL too? I always thought it is only true for LGPL.

**Comment by SahilKang** [comment]
you should consult a lawyer to be sure about your specific use-case but generally:
* if you use this lib in a binary and then distribute that binary to users, that binary has to be licensed under the gpl like this lib
* if you use this lib in a binary and only keep that binary on a server instead of distributing it to users, then you don't have to license that binary...since you're not sharing it with users

to learn more, you can compare the gpl with the agpl, the latter would require licensing the server binary even if it's not distributed to users

kafka clusters are usually not exposed to the public internet so whichever one of your binaries is using this lib will most likely remain on one of your servers instead of being distributed to users...and if that binary isn't distributed, it doesn't have to be licensed
